options:
  logging: CLOUD_LOGGING_ONLY

steps:

- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/unnati-repo/form-app:$COMMIT_SHA
    - .

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/unnati-repo/form-app:$COMMIT_SHA

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - form-app
    - --image
    - asia-south1-docker.pkg.dev/$PROJECT_ID/unnati-repo/form-app:$COMMIT_SHA
    - --region
    - asia-south1
    - --platform
    - managed
    - --allow-unauthenticated

images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/unnati-repo/form-app:$COMMIT_SHA
